#服务端口
server:
  port: 18080
spring:
  application:
    name: tanhua-app-server
  redis:  #redis配置
    port: 6379
    host: 192.168.136.160
  cloud:  #nacos配置
    nacos:
      discovery:
        server-addr: 192.168.136.160:8848
dubbo:    #dubbo配置
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
#tanhua:
#  sms:
#    signName: 物流云商
#    templateCode: SMS_106590012
#    accessKey: LTAI4GKgob9vZ53k2SZdyAC7
#    secret: LHLBvXmILRoyw0niRSBuXBZewQ30la
tanhua:
  sms:
    signName: 物流云商
    templateCode: SMS_106590012
    accessKey: LTAI4GKgob9vZ53k2SZdyAC7
    secret: LHLBvXmILRoyw0niRSBuXBZewQ30la
  oss:
    accessKey: LTAI5t5s6pJdWd9tkXoZqAr8
    secret: 5VEyyDnmMg6pMwsBIwFNcDWdEouVK8
    bucketName: jgstanhua
    url: https://jgstanhua.oss-cn-beijing.aliyuncs.com/
    endpoint: oss-cn-beijing.aliyuncs.com
  aip:
    appId: 26037091
    apiKey: cFk6x2fCVn57ySrcwCRsBo78
    secretKey: Sz0uza2eGhj2ZU971mBfHQHo1LIthMsA
  huanxin:
    appkey: 1143220502140452#tanhua1
    clientId: YXA6IDiLzNY6R8aVPA4PYTtOmw
    clientSecret: YXA6Iy1XKSLUsYA0eeKM-XaP6g4bsEs

# huanxin:
#   appkey: 1149210719148468#tanhua1
#   clientId: YXA6g0RNzRzcRMuD5oLQiCyw5w
#   clientSecret: YXA6N2NhMGdk2v3f9qIrxjw4t8H-p8A
recommend:
  uid: 1